// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gphotosuploader/google-photos-api-client-go/v3 (interfaces: MediaUploader)

// Package commands is a generated GoMock package.
package lib

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMediaUploader is a mock of MediaUploader interface.
type MockMediaUploader struct {
	ctrl     *gomock.Controller
	recorder *MockMediaUploaderMockRecorder
}

// MockMediaUploaderMockRecorder is the mock recorder for MockMediaUploader.
type MockMediaUploaderMockRecorder struct {
	mock *MockMediaUploader
}

// NewMockMediaUploader creates a new mock instance.
func NewMockMediaUploader(ctrl *gomock.Controller) *MockMediaUploader {
	mock := &MockMediaUploader{ctrl: ctrl}
	mock.recorder = &MockMediaUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaUploader) EXPECT() *MockMediaUploaderMockRecorder {
	return m.recorder
}

// UploadFile mocks base method.
func (m *MockMediaUploader) UploadFile(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockMediaUploaderMockRecorder) UploadFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockMediaUploader)(nil).UploadFile), arg0, arg1)
}
