// Code generated by MockGen. DO NOT EDIT.
// Source: gphotos_client_interface.go

// Package commands is a generated GoMock package.
package lib

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v3 "github.com/gphotosuploader/google-photos-api-client-go/v3"
	albums "github.com/gphotosuploader/google-photos-api-client-go/v3/albums"
	media_items "github.com/gphotosuploader/google-photos-api-client-go/v3/media_items"
)

// MockGPhotosClient is a mock of GPhotosClient interface.
type MockGPhotosClient struct {
	ctrl     *gomock.Controller
	recorder *MockGPhotosClientMockRecorder
}

// MockGPhotosClientMockRecorder is the mock recorder for MockGPhotosClient.
type MockGPhotosClientMockRecorder struct {
	mock *MockGPhotosClient
}

// NewMockGPhotosClient creates a new mock instance.
func NewMockGPhotosClient(ctrl *gomock.Controller) *MockGPhotosClient {
	mock := &MockGPhotosClient{ctrl: ctrl}
	mock.recorder = &MockGPhotosClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPhotosClient) EXPECT() *MockGPhotosClientMockRecorder {
	return m.recorder
}

// Albums mocks base method.
func (m *MockGPhotosClient) Albums() AppAlbumsService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Albums")
	ret0, _ := ret[0].(AppAlbumsService)
	return ret0
}

// Albums indicates an expected call of Albums.
func (mr *MockGPhotosClientMockRecorder) Albums() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Albums", reflect.TypeOf((*MockGPhotosClient)(nil).Albums))
}

// MediaItems mocks base method.
func (m *MockGPhotosClient) MediaItems() AppMediaItemsService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MediaItems")
	ret0, _ := ret[0].(AppMediaItemsService)
	return ret0
}

// MediaItems indicates an expected call of MediaItems.
func (mr *MockGPhotosClientMockRecorder) MediaItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MediaItems", reflect.TypeOf((*MockGPhotosClient)(nil).MediaItems))
}

// Uploader mocks base method.
func (m *MockGPhotosClient) Uploader() v3.MediaUploader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uploader")
	ret0, _ := ret[0].(v3.MediaUploader)
	return ret0
}

// Uploader indicates an expected call of Uploader.
func (mr *MockGPhotosClientMockRecorder) Uploader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uploader", reflect.TypeOf((*MockGPhotosClient)(nil).Uploader))
}

// MockAppAlbumsService is a mock of AppAlbumsService interface.
type MockAppAlbumsService struct {
	ctrl     *gomock.Controller
	recorder *MockAppAlbumsServiceMockRecorder
}

// MockAppAlbumsServiceMockRecorder is the mock recorder for MockAppAlbumsService.
type MockAppAlbumsServiceMockRecorder struct {
	mock *MockAppAlbumsService
}

// NewMockAppAlbumsService creates a new mock instance.
func NewMockAppAlbumsService(ctrl *gomock.Controller) *MockAppAlbumsService {
	mock := &MockAppAlbumsService{ctrl: ctrl}
	mock.recorder = &MockAppAlbumsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppAlbumsService) EXPECT() *MockAppAlbumsServiceMockRecorder {
	return m.recorder
}

// AddMediaItems mocks base method.
func (m *MockAppAlbumsService) AddMediaItems(ctx context.Context, albumID string, mediaItemIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMediaItems", ctx, albumID, mediaItemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMediaItems indicates an expected call of AddMediaItems.
func (mr *MockAppAlbumsServiceMockRecorder) AddMediaItems(ctx, albumID, mediaItemIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMediaItems", reflect.TypeOf((*MockAppAlbumsService)(nil).AddMediaItems), ctx, albumID, mediaItemIDs)
}

// Create mocks base method.
func (m *MockAppAlbumsService) Create(ctx context.Context, title string) (*albums.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, title)
	ret0, _ := ret[0].(*albums.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAppAlbumsServiceMockRecorder) Create(ctx, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppAlbumsService)(nil).Create), ctx, title)
}

// List mocks base method.
func (m *MockAppAlbumsService) List(ctx context.Context) ([]albums.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]albums.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAppAlbumsServiceMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAppAlbumsService)(nil).List), ctx)
}

// MockAppMediaItemsService is a mock of AppMediaItemsService interface.
type MockAppMediaItemsService struct {
	ctrl     *gomock.Controller
	recorder *MockAppMediaItemsServiceMockRecorder
}

// MockAppMediaItemsServiceMockRecorder is the mock recorder for MockAppMediaItemsService.
type MockAppMediaItemsServiceMockRecorder struct {
	mock *MockAppMediaItemsService
}

// NewMockAppMediaItemsService creates a new mock instance.
func NewMockAppMediaItemsService(ctrl *gomock.Controller) *MockAppMediaItemsService {
	mock := &MockAppMediaItemsService{ctrl: ctrl}
	mock.recorder = &MockAppMediaItemsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppMediaItemsService) EXPECT() *MockAppMediaItemsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppMediaItemsService) Create(ctx context.Context, item media_items.SimpleMediaItem) (*media_items.MediaItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(*media_items.MediaItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAppMediaItemsServiceMockRecorder) Create(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppMediaItemsService)(nil).Create), ctx, item)
}
